platform :ios, '8.0'
use_frameworks!

pod 'RealmSwift'
pod 'EasyAnimation'
pod 'JVFloatLabeledTextField'

target 'GymWorkoutManager' do

end

target 'GymWorkoutManagerTests' do

end

target 'GymWorkoutManagerUITests' do

end

